
version: 2

models:
  - name: stg__apprenticeship_users
    description: "apprenticeship users"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: stg__ash_questions
    description: "questions given to the users"
    columns:
      - name: question_id
        description: "unique question id for each user"
        data_tests:
          - unique
          - not_null
